import type { LetterFormData } from "../types";
import { LETTER_TYPE_CONFIG } from "../types";

export interface PDFLetterData {
  formData: LetterFormData;
  letterContent: string;
  watermark?: boolean;
}

/** Format the letter content with letterhead into a full HTML document */
export function buildLetterHTML(data: PDFLetterData): string {
  const { formData, letterContent, watermark } = data;
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const letterTypeLabel = formData.letterType
    ? LETTER_TYPE_CONFIG[formData.letterType].label
    : "Demand";

  const watermarkStyle = watermark
    ? `
    <style>
      body::after {
        content: "Sue Letter";
        position: fixed;
        bottom: 80px;
        right: 40px;
        font-size: 10px;
        color: #ccc;
        letter-spacing: 2px;
        text-transform: uppercase;
        transform: rotate(-30deg);
        pointer-events: none;
        opacity: 0.5;
      }
    </style>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Demand Letter — ${letterTypeLabel}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=DM+Mono&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'DM Sans', Arial, sans-serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #1a1a2e;
      background: #fff;
      padding: 72px 80px;
      max-width: 760px;
      margin: 0 auto;
    }
    .letterhead {
      border-bottom: 2px solid #0A2342;
      padding-bottom: 16px;
      margin-bottom: 24px;
    }
    .sender-name {
      font-size: 14pt;
      font-weight: 600;
      color: #0A2342;
    }
    .sender-details {
      font-size: 10pt;
      color: #555;
      margin-top: 4px;
    }
    .date-block { margin-bottom: 24px; font-size: 11pt; }
    .recipient-block { margin-bottom: 24px; }
    .recipient-name { font-weight: 600; }
    .re-line {
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.04em;
      font-size: 10pt;
      margin-bottom: 24px;
      padding: 8px 12px;
      background: #f4f6fb;
      border-left: 4px solid #0A2342;
    }
    .body { white-space: pre-wrap; line-height: 1.7; }
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #ddd;
      font-size: 9pt;
      color: #888;
      text-align: center;
    }
    @media print {
      body { padding: 48px; }
    }
  </style>
  ${watermarkStyle}
</head>
<body>
  <div class="letterhead">
    <div class="sender-name">${escapeHTML(formData.senderName)}</div>
    <div class="sender-details">
      ${escapeHTML(formData.senderAddress)}, ${escapeHTML(formData.senderCity)}, ${escapeHTML(formData.senderState)} ${escapeHTML(formData.senderZip)}<br>
      ${formData.senderPhone ? `Tel: ${escapeHTML(formData.senderPhone)} &nbsp;|&nbsp; ` : ""}${formData.senderEmail ? `Email: ${escapeHTML(formData.senderEmail)}` : ""}
    </div>
  </div>

  <div class="date-block">${today}</div>

  <div class="recipient-block">
    <div class="recipient-name">${escapeHTML(formData.recipientName)}</div>
    ${formData.recipientCompany ? `<div>${escapeHTML(formData.recipientCompany)}</div>` : ""}
    ${formData.recipientTitle ? `<div>${escapeHTML(formData.recipientTitle)}</div>` : ""}
    <div>${escapeHTML(formData.recipientAddress)}</div>
    <div>${escapeHTML(formData.recipientCity)}${formData.recipientState ? `, ${escapeHTML(formData.recipientState)}` : ""} ${escapeHTML(formData.recipientZip)}</div>
  </div>

  <div class="re-line">Re: ${letterTypeLabel} — Formal Demand for Resolution</div>

  <div class="body">${escapeHTML(letterContent)}</div>

  <div class="footer">
    Generated by Sue Letter — This document is not legal advice. | ${today}
    ${watermark ? " | Free Plan — Upgrade at sueletter.com for a clean copy" : ""}
  </div>
</body>
</html>`;
}

/** Build null-byte regex via constructor to avoid ESLint/TSC control-char complaints */
const NULL_BYTES_REGEX = new RegExp(String.fromCharCode(0), "g");
const DIRECTION_OVERRIDES_REGEX = /[\u202E\u200F\u200E]/g;
const MAX_FIELD_LENGTH = 100_000;

function escapeHTML(str: string): string {
  if (!str) return "";
  // Truncate, strip null bytes and direction-override characters first
  const sanitized = str
    .slice(0, MAX_FIELD_LENGTH)
    .replace(NULL_BYTES_REGEX, "")
    .replace(DIRECTION_OVERRIDES_REGEX, "");
  return sanitized
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/** Opens a print dialog with the formatted letter */
export function printLetter(data: PDFLetterData): void {
  const html = buildLetterHTML(data);
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;
  win.document.write(html);
  win.document.close();
  win.focus();
  win.onload = () => {
    win.print();
  };
}

/** Copy the plain letter text to clipboard */
export async function copyLetterText(letterContent: string): Promise<void> {
  await navigator.clipboard.writeText(letterContent);
}
