import { Lock } from "lucide-react";

interface LegalDisclaimerProps {
  compact?: boolean;
  className?: string;
}

export function LegalDisclaimer({
  compact = false,
  className = "",
}: LegalDisclaimerProps) {
  if (compact) {
    return (
      <p className={`legal-disclaimer flex items-start gap-1.5 ${className}`}>
        <Lock
          className="w-3 h-3 mt-0.5 shrink-0 text-muted-foreground"
          aria-hidden="true"
        />
        <span>
          Not legal advice. No attorney-client relationship is formed. Consult a
          licensed attorney in your jurisdiction for legal matters.
        </span>
      </p>
    );
  }

  return (
    <div className={`legal-disclaimer ${className}`}>
      <div className="flex items-start gap-2">
        <Lock
          className="w-3.5 h-3.5 mt-0.5 shrink-0 text-muted-foreground"
          aria-hidden="true"
        />
        <p>
          <strong className="font-medium text-foreground">
            Legal Disclaimer:
          </strong>{" "}
          The letters generated by this tool are for informational purposes only
          and do not constitute legal advice. No attorney-client relationship is
          formed by using this service. For legal matters, please consult a
          licensed attorney in your jurisdiction. Sue Letter is not a law firm
          and does not provide legal representation.
        </p>
      </div>
    </div>
  );
}
