/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LetterId = IDL.Text;
export const Result_4 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogCategory = IDL.Variant({
  'Insurance' : IDL.Null,
  'Debt' : IDL.Null,
  'Refund' : IDL.Null,
  'CeaseDesist' : IDL.Null,
  'PropertyDamage' : IDL.Null,
  'Employment' : IDL.Null,
  'Landlord' : IDL.Null,
  'Contractor' : IDL.Null,
});
export const CreateArticleInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'slug' : IDL.Text,
  'authorName' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : BlogCategory,
});
export const BlogArticle = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'slug' : IDL.Text,
  'authorName' : IDL.Text,
  'publishedAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'excerpt' : IDL.Text,
  'category' : BlogCategory,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const UserPlan = IDL.Variant({
  'Pro' : IDL.Null,
  'PayPerLetter' : IDL.Null,
  'Free' : IDL.Null,
  'Business' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'userId' : UserId,
  'createdAt' : Timestamp,
  'plan' : UserPlan,
  'email' : IDL.Opt(IDL.Text),
  'lettersThisMonth' : IDL.Nat,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'totalLetters' : IDL.Nat,
  'currentMonthYear' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const LetterTone = IDL.Variant({
  'Firm' : IDL.Null,
  'Assertive' : IDL.Null,
  'FinalWarning' : IDL.Null,
});
export const LetterType = IDL.Variant({
  'DebtRecovery' : IDL.Null,
  'LandlordTenant' : IDL.Null,
  'CeaseDesist' : IDL.Null,
  'ContractorDispute' : IDL.Null,
  'InsuranceClaim' : IDL.Null,
  'PropertyDamage' : IDL.Null,
  'RefundConsumer' : IDL.Null,
  'EmploymentDispute' : IDL.Null,
  'CreditReportDispute' : IDL.Null,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const PriorContact = IDL.Record({
  'method' : IDL.Text,
  'attempted' : IDL.Bool,
  'count' : IDL.Nat,
});
export const LetterFormData = IDL.Record({
  'inaccuracyType' : IDL.Opt(IDL.Text),
  'senderPhone' : IDL.Text,
  'deadlineDays' : IDL.Nat,
  'tone' : LetterTone,
  'disputeDescription' : IDL.Text,
  'letterType' : LetterType,
  'creditSupportingDocs' : IDL.Opt(IDL.Vec(IDL.Text)),
  'creditDisputeDescription' : IDL.Opt(IDL.Text),
  'evidenceItems' : IDL.Vec(IDL.Text),
  'amountDemanded' : IDL.Opt(IDL.Nat),
  'evidenceImages' : IDL.Vec(IDL.Text),
  'jurisdiction' : IDL.Text,
  'accountName' : IDL.Opt(IDL.Text),
  'currency' : IDL.Text,
  'preferredResolution' : IDL.Text,
  'senderName' : IDL.Text,
  'accountNumber' : IDL.Opt(IDL.Text),
  'senderEmail' : IDL.Text,
  'recipientAddress' : Address,
  'recipientName' : IDL.Text,
  'recipientRole' : IDL.Text,
  'priorContact' : PriorContact,
  'senderAddress' : Address,
  'incidentDate' : IDL.Text,
  'creditBureauName' : IDL.Opt(IDL.Text),
});
export const ResponseLikelihood = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const StrengthAnalysis = IDL.Record({
  'responseLikelihood' : ResponseLikelihood,
  'strengths' : IDL.Vec(IDL.Text),
  'improvements' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
});
export const Result_3 = IDL.Variant({
  'ok' : StrengthAnalysis,
  'err' : IDL.Text,
});
export const GmailToken = IDL.Record({
  'expiresAt' : Timestamp,
  'refreshToken' : IDL.Text,
  'accessToken' : IDL.Text,
});
export const LetterStatus = IDL.Variant({
  'Sent' : IDL.Null,
  'Draft' : IDL.Null,
  'ResponseReceived' : IDL.Null,
  'FollowUpNeeded' : IDL.Null,
  'Resolved' : IDL.Null,
});
export const GeneratedLetter = IDL.Record({
  'id' : LetterId,
  'status' : LetterStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'formData' : LetterFormData,
  'letterContent' : IDL.Text,
  'originalLetterId' : IDL.Opt(LetterId),
  'downloadCount' : IDL.Nat,
  'lastDownloadAt' : IDL.Opt(IDL.Int),
  'isFollowUp' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const PartnershipRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
});
export const Result_2 = IDL.Variant({
  'ok' : GeneratedLetter,
  'err' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const CreatePartnershipRequestInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'preferredDate' : IDL.Text,
  'preferredTime' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateArticleInput = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'content' : IDL.Opt(IDL.Text),
  'isPublished' : IDL.Opt(IDL.Bool),
  'authorName' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(BlogCategory),
});
export const StripePlan = IDL.Variant({
  'Pro' : IDL.Null,
  'Business' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'answerQuestion' : IDL.Func([IDL.Text, LetterId], [Result_4], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canGenerateLetter' : IDL.Func(
      [],
      [
        IDL.Record({
          'canGenerate' : IDL.Bool,
          'remaining' : IDL.Nat,
          'reason' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'createArticle' : IDL.Func(
      [CreateArticleInput],
      [IDL.Variant({ 'ok' : BlogArticle, 'err' : IDL.Text })],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrUpdateUser' : IDL.Func([IDL.Opt(IDL.Text)], [UserProfile], []),
  'deleteLetterForUser' : IDL.Func([LetterId], [Result], []),
  'generateFollowUpLetter' : IDL.Func([LetterId], [Result_4], []),
  'generateLetterStream' : IDL.Func(
      [LetterFormData, IDL.Opt(IDL.Text)],
      [Result_4],
      [],
    ),
  'generateStrengthAnalysis' : IDL.Func([LetterId], [Result_3], []),
  'getAdminStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalLetters' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'activeSubscriptions' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getArticleBySlug' : IDL.Func([IDL.Text], [IDL.Opt(BlogArticle)], ['query']),
  'getAuditLog' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Timestamp, IDL.Text, IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGmailToken' : IDL.Func([], [IDL.Opt(GmailToken)], ['query']),
  'getLetter' : IDL.Func([LetterId], [IDL.Opt(GeneratedLetter)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserLetters' : IDL.Func([], [IDL.Vec(GeneratedLetter)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'isAnthropicConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listArticles' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(BlogArticle)],
      ['query'],
    ),
  'listPartnershipRequests' : IDL.Func([], [IDL.Vec(PartnershipRequest)], []),
  'recordDownload' : IDL.Func([LetterId], [Result], []),
  'saveLetter' : IDL.Func([LetterFormData, IDL.Text], [Result_2], []),
  'sendLetterViaGmail' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'setAnthropicKey' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'storeGmailToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [Result_1], []),
  'submitPartnershipRequest' : IDL.Func(
      [CreatePartnershipRequestInput],
      [IDL.Variant({ 'ok' : PartnershipRequest, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateArticle' : IDL.Func(
      [IDL.Text, UpdateArticleInput],
      [IDL.Variant({ 'ok' : BlogArticle, 'err' : IDL.Text })],
      [],
    ),
  'updateLetterStatus' : IDL.Func([LetterId, LetterStatus], [Result], []),
  'updateUserPlan' : IDL.Func([UserId, StripePlan], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LetterId = IDL.Text;
  const Result_4 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogCategory = IDL.Variant({
    'Insurance' : IDL.Null,
    'Debt' : IDL.Null,
    'Refund' : IDL.Null,
    'CeaseDesist' : IDL.Null,
    'PropertyDamage' : IDL.Null,
    'Employment' : IDL.Null,
    'Landlord' : IDL.Null,
    'Contractor' : IDL.Null,
  });
  const CreateArticleInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'slug' : IDL.Text,
    'authorName' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : BlogCategory,
  });
  const BlogArticle = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'slug' : IDL.Text,
    'authorName' : IDL.Text,
    'publishedAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'excerpt' : IDL.Text,
    'category' : BlogCategory,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const UserPlan = IDL.Variant({
    'Pro' : IDL.Null,
    'PayPerLetter' : IDL.Null,
    'Free' : IDL.Null,
    'Business' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'userId' : UserId,
    'createdAt' : Timestamp,
    'plan' : UserPlan,
    'email' : IDL.Opt(IDL.Text),
    'lettersThisMonth' : IDL.Nat,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'totalLetters' : IDL.Nat,
    'currentMonthYear' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const LetterTone = IDL.Variant({
    'Firm' : IDL.Null,
    'Assertive' : IDL.Null,
    'FinalWarning' : IDL.Null,
  });
  const LetterType = IDL.Variant({
    'DebtRecovery' : IDL.Null,
    'LandlordTenant' : IDL.Null,
    'CeaseDesist' : IDL.Null,
    'ContractorDispute' : IDL.Null,
    'InsuranceClaim' : IDL.Null,
    'PropertyDamage' : IDL.Null,
    'RefundConsumer' : IDL.Null,
    'EmploymentDispute' : IDL.Null,
    'CreditReportDispute' : IDL.Null,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const PriorContact = IDL.Record({
    'method' : IDL.Text,
    'attempted' : IDL.Bool,
    'count' : IDL.Nat,
  });
  const LetterFormData = IDL.Record({
    'inaccuracyType' : IDL.Opt(IDL.Text),
    'senderPhone' : IDL.Text,
    'deadlineDays' : IDL.Nat,
    'tone' : LetterTone,
    'disputeDescription' : IDL.Text,
    'letterType' : LetterType,
    'creditSupportingDocs' : IDL.Opt(IDL.Vec(IDL.Text)),
    'creditDisputeDescription' : IDL.Opt(IDL.Text),
    'evidenceItems' : IDL.Vec(IDL.Text),
    'amountDemanded' : IDL.Opt(IDL.Nat),
    'evidenceImages' : IDL.Vec(IDL.Text),
    'jurisdiction' : IDL.Text,
    'accountName' : IDL.Opt(IDL.Text),
    'currency' : IDL.Text,
    'preferredResolution' : IDL.Text,
    'senderName' : IDL.Text,
    'accountNumber' : IDL.Opt(IDL.Text),
    'senderEmail' : IDL.Text,
    'recipientAddress' : Address,
    'recipientName' : IDL.Text,
    'recipientRole' : IDL.Text,
    'priorContact' : PriorContact,
    'senderAddress' : Address,
    'incidentDate' : IDL.Text,
    'creditBureauName' : IDL.Opt(IDL.Text),
  });
  const ResponseLikelihood = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const StrengthAnalysis = IDL.Record({
    'responseLikelihood' : ResponseLikelihood,
    'strengths' : IDL.Vec(IDL.Text),
    'improvements' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
  });
  const Result_3 = IDL.Variant({ 'ok' : StrengthAnalysis, 'err' : IDL.Text });
  const GmailToken = IDL.Record({
    'expiresAt' : Timestamp,
    'refreshToken' : IDL.Text,
    'accessToken' : IDL.Text,
  });
  const LetterStatus = IDL.Variant({
    'Sent' : IDL.Null,
    'Draft' : IDL.Null,
    'ResponseReceived' : IDL.Null,
    'FollowUpNeeded' : IDL.Null,
    'Resolved' : IDL.Null,
  });
  const GeneratedLetter = IDL.Record({
    'id' : LetterId,
    'status' : LetterStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'formData' : LetterFormData,
    'letterContent' : IDL.Text,
    'originalLetterId' : IDL.Opt(LetterId),
    'downloadCount' : IDL.Nat,
    'lastDownloadAt' : IDL.Opt(IDL.Int),
    'isFollowUp' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const PartnershipRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : GeneratedLetter, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const CreatePartnershipRequestInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'preferredDate' : IDL.Text,
    'preferredTime' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateArticleInput = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'content' : IDL.Opt(IDL.Text),
    'isPublished' : IDL.Opt(IDL.Bool),
    'authorName' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(BlogCategory),
  });
  const StripePlan = IDL.Variant({ 'Pro' : IDL.Null, 'Business' : IDL.Null });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'answerQuestion' : IDL.Func([IDL.Text, LetterId], [Result_4], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canGenerateLetter' : IDL.Func(
        [],
        [
          IDL.Record({
            'canGenerate' : IDL.Bool,
            'remaining' : IDL.Nat,
            'reason' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'createArticle' : IDL.Func(
        [CreateArticleInput],
        [IDL.Variant({ 'ok' : BlogArticle, 'err' : IDL.Text })],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrUpdateUser' : IDL.Func([IDL.Opt(IDL.Text)], [UserProfile], []),
    'deleteLetterForUser' : IDL.Func([LetterId], [Result], []),
    'generateFollowUpLetter' : IDL.Func([LetterId], [Result_4], []),
    'generateLetterStream' : IDL.Func(
        [LetterFormData, IDL.Opt(IDL.Text)],
        [Result_4],
        [],
      ),
    'generateStrengthAnalysis' : IDL.Func([LetterId], [Result_3], []),
    'getAdminStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalLetters' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'activeSubscriptions' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getArticleBySlug' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(BlogArticle)],
        ['query'],
      ),
    'getAuditLog' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Timestamp, IDL.Text, IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGmailToken' : IDL.Func([], [IDL.Opt(GmailToken)], ['query']),
    'getLetter' : IDL.Func([LetterId], [IDL.Opt(GeneratedLetter)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserLetters' : IDL.Func([], [IDL.Vec(GeneratedLetter)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'isAnthropicConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listArticles' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(BlogArticle)],
        ['query'],
      ),
    'listPartnershipRequests' : IDL.Func([], [IDL.Vec(PartnershipRequest)], []),
    'recordDownload' : IDL.Func([LetterId], [Result], []),
    'saveLetter' : IDL.Func([LetterFormData, IDL.Text], [Result_2], []),
    'sendLetterViaGmail' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'setAnthropicKey' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'storeGmailToken' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [Result_1], []),
    'submitPartnershipRequest' : IDL.Func(
        [CreatePartnershipRequestInput],
        [IDL.Variant({ 'ok' : PartnershipRequest, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateArticle' : IDL.Func(
        [IDL.Text, UpdateArticleInput],
        [IDL.Variant({ 'ok' : BlogArticle, 'err' : IDL.Text })],
        [],
      ),
    'updateLetterStatus' : IDL.Func([LetterId, LetterStatus], [Result], []),
    'updateUserPlan' : IDL.Func([UserId, StripePlan], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };