/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'city' : string,
  'state' : string,
}
export interface BlogArticle {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'authorName' : string,
  'publishedAt' : bigint,
  'updatedAt' : bigint,
  'excerpt' : string,
  'category' : BlogCategory,
}
export type BlogCategory = { 'Insurance' : null } |
  { 'Debt' : null } |
  { 'Refund' : null } |
  { 'CeaseDesist' : null } |
  { 'PropertyDamage' : null } |
  { 'Employment' : null } |
  { 'Landlord' : null } |
  { 'Contractor' : null };
export interface CreateArticleInput {
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'slug' : string,
  'authorName' : string,
  'excerpt' : string,
  'category' : BlogCategory,
}
export interface CreatePartnershipRequestInput {
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'preferredDate' : string,
  'preferredTime' : string,
}
export interface GeneratedLetter {
  'id' : LetterId,
  'status' : LetterStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'formData' : LetterFormData,
  'letterContent' : string,
  'originalLetterId' : [] | [LetterId],
  'downloadCount' : bigint,
  'lastDownloadAt' : [] | [bigint],
  'isFollowUp' : boolean,
}
export interface GmailToken {
  'expiresAt' : Timestamp,
  'refreshToken' : string,
  'accessToken' : string,
}
export interface LetterFormData {
  'inaccuracyType' : [] | [string],
  'senderPhone' : string,
  'deadlineDays' : bigint,
  'tone' : LetterTone,
  'disputeDescription' : string,
  'letterType' : LetterType,
  'creditSupportingDocs' : [] | [Array<string>],
  'creditDisputeDescription' : [] | [string],
  'evidenceItems' : Array<string>,
  'amountDemanded' : [] | [bigint],
  'evidenceImages' : Array<string>,
  'jurisdiction' : string,
  'accountName' : [] | [string],
  'currency' : string,
  'preferredResolution' : string,
  'senderName' : string,
  'accountNumber' : [] | [string],
  'senderEmail' : string,
  'recipientAddress' : Address,
  'recipientName' : string,
  'recipientRole' : string,
  'priorContact' : PriorContact,
  'senderAddress' : Address,
  'incidentDate' : string,
  'creditBureauName' : [] | [string],
}
export type LetterId = string;
export type LetterStatus = { 'Sent' : null } |
  { 'Draft' : null } |
  { 'ResponseReceived' : null } |
  { 'FollowUpNeeded' : null } |
  { 'Resolved' : null };
export type LetterTone = { 'Firm' : null } |
  { 'Assertive' : null } |
  { 'FinalWarning' : null };
export type LetterType = { 'DebtRecovery' : null } |
  { 'LandlordTenant' : null } |
  { 'CeaseDesist' : null } |
  { 'ContractorDispute' : null } |
  { 'InsuranceClaim' : null } |
  { 'PropertyDamage' : null } |
  { 'RefundConsumer' : null } |
  { 'EmploymentDispute' : null } |
  { 'CreditReportDispute' : null };
export interface PartnershipRequest {
  'id' : string,
  'status' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'company' : string,
  'message' : string,
  'preferredDate' : string,
  'preferredTime' : string,
}
export interface PriorContact {
  'method' : string,
  'attempted' : boolean,
  'count' : bigint,
}
export type ResponseLikelihood = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export type Result = { 'ok' : boolean } |
  { 'err' : string };
export type Result_1 = { 'ok' : null } |
  { 'err' : string };
export type Result_2 = { 'ok' : GeneratedLetter } |
  { 'err' : string };
export type Result_3 = { 'ok' : StrengthAnalysis } |
  { 'err' : string };
export type Result_4 = { 'ok' : string } |
  { 'err' : string };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StrengthAnalysis {
  'responseLikelihood' : ResponseLikelihood,
  'strengths' : Array<string>,
  'improvements' : Array<string>,
  'score' : bigint,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripePlan = { 'Pro' : null } |
  { 'Business' : null };
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateArticleInput {
  'title' : [] | [string],
  'content' : [] | [string],
  'isPublished' : [] | [boolean],
  'authorName' : [] | [string],
  'excerpt' : [] | [string],
  'category' : [] | [BlogCategory],
}
export type UserId = string;
export type UserPlan = { 'Pro' : null } |
  { 'PayPerLetter' : null } |
  { 'Free' : null } |
  { 'Business' : null };
export interface UserProfile {
  'stripeSubscriptionId' : [] | [string],
  'userId' : UserId,
  'createdAt' : Timestamp,
  'plan' : UserPlan,
  'email' : [] | [string],
  'lettersThisMonth' : bigint,
  'stripeCustomerId' : [] | [string],
  'totalLetters' : bigint,
  'currentMonthYear' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'answerQuestion' : ActorMethod<[string, LetterId], Result_4>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canGenerateLetter' : ActorMethod<
    [],
    { 'canGenerate' : boolean, 'remaining' : bigint, 'reason' : string }
  >,
  'createArticle' : ActorMethod<
    [CreateArticleInput],
    { 'ok' : BlogArticle } |
      { 'err' : string }
  >,
  /**
   * / Create a Stripe Checkout session for a pay-per-letter or plan upgrade.
   * / Returns Stripe session JSON (contains `url` to redirect the user).
   */
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrUpdateUser' : ActorMethod<[[] | [string]], UserProfile>,
  'deleteLetterForUser' : ActorMethod<[LetterId], Result>,
  'generateFollowUpLetter' : ActorMethod<[LetterId], Result_4>,
  'generateLetterStream' : ActorMethod<
    [LetterFormData, [] | [string]],
    Result_4
  >,
  'generateStrengthAnalysis' : ActorMethod<[LetterId], Result_3>,
  'getAdminStats' : ActorMethod<
    [],
    {
      'totalLetters' : bigint,
      'totalUsers' : bigint,
      'activeSubscriptions' : bigint,
    }
  >,
  'getArticleBySlug' : ActorMethod<[string], [] | [BlogArticle]>,
  'getAuditLog' : ActorMethod<[], Array<[Timestamp, string, string, string]>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGmailToken' : ActorMethod<[], [] | [GmailToken]>,
  'getLetter' : ActorMethod<[LetterId], [] | [GeneratedLetter]>,
  /**
   * / Check payment status for a given Stripe session ID.
   */
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserLetters' : ActorMethod<[], Array<GeneratedLetter>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'isAnthropicConfigured' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Check whether Stripe has been configured.
   */
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listArticles' : ActorMethod<[[] | [string]], Array<BlogArticle>>,
  'listPartnershipRequests' : ActorMethod<[], Array<PartnershipRequest>>,
  'recordDownload' : ActorMethod<[LetterId], Result>,
  'saveLetter' : ActorMethod<[LetterFormData, string], Result_2>,
  'sendLetterViaGmail' : ActorMethod<[string, string, string], Result_1>,
  'setAnthropicKey' : ActorMethod<[string], undefined>,
  /**
   * / Store the Stripe secret key and allowed countries (admin only).
   */
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'storeGmailToken' : ActorMethod<[string, string, bigint], Result_1>,
  'submitPartnershipRequest' : ActorMethod<
    [CreatePartnershipRequestInput],
    { 'ok' : PartnershipRequest } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArticle' : ActorMethod<
    [string, UpdateArticleInput],
    { 'ok' : BlogArticle } |
      { 'err' : string }
  >,
  'updateLetterStatus' : ActorMethod<[LetterId, LetterStatus], Result>,
  'updateUserPlan' : ActorMethod<[UserId, StripePlan], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];