/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Result_2 = {
    __kind__: "ok";
    ok: GeneratedLetter;
} | {
    __kind__: "err";
    err: string;
};
export interface BlogArticle {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    authorName: string;
    publishedAt: bigint;
    updatedAt: bigint;
    excerpt: string;
    category: BlogCategory;
}
export interface GeneratedLetter {
    id: LetterId;
    status: LetterStatus;
    userId: UserId;
    createdAt: Timestamp;
    formData: LetterFormData;
    letterContent: string;
    originalLetterId?: LetterId;
    downloadCount: bigint;
    lastDownloadAt?: bigint;
    isFollowUp: boolean;
}
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface CreateArticleInput {
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    authorName: string;
    excerpt: string;
    category: BlogCategory;
}
export type Result_4 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface LetterFormData {
    inaccuracyType?: string;
    senderPhone: string;
    deadlineDays: bigint;
    tone: LetterTone;
    disputeDescription: string;
    letterType: LetterType;
    creditSupportingDocs?: Array<string>;
    creditDisputeDescription?: string;
    evidenceItems: Array<string>;
    amountDemanded?: bigint;
    evidenceImages: Array<string>;
    jurisdiction: string;
    accountName?: string;
    currency: string;
    preferredResolution: string;
    senderName: string;
    accountNumber?: string;
    senderEmail: string;
    recipientAddress: Address;
    recipientName: string;
    recipientRole: string;
    priorContact: PriorContact;
    senderAddress: Address;
    incidentDate: string;
    creditBureauName?: string;
}
export interface UpdateArticleInput {
    title?: string;
    content?: string;
    isPublished?: boolean;
    authorName?: string;
    excerpt?: string;
    category?: BlogCategory;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface PartnershipRequest {
    id: string;
    status: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    company: string;
    message: string;
    preferredDate: string;
    preferredTime: string;
}
export interface GmailToken {
    expiresAt: Timestamp;
    refreshToken: string;
    accessToken: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = string;
export interface CreatePartnershipRequestInput {
    name: string;
    email: string;
    company: string;
    message: string;
    preferredDate: string;
    preferredTime: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type Result_3 = {
    __kind__: "ok";
    ok: StrengthAnalysis;
} | {
    __kind__: "err";
    err: string;
};
export interface StrengthAnalysis {
    responseLikelihood: ResponseLikelihood;
    strengths: Array<string>;
    improvements: Array<string>;
    score: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface PriorContact {
    method: string;
    attempted: boolean;
    count: bigint;
}
export type LetterId = string;
export interface UserProfile {
    stripeSubscriptionId?: string;
    userId: UserId;
    createdAt: Timestamp;
    plan: UserPlan;
    email?: string;
    lettersThisMonth: bigint;
    stripeCustomerId?: string;
    totalLetters: bigint;
    currentMonthYear: string;
}
export interface Address {
    zip: string;
    street: string;
    city: string;
    state: string;
}
export enum BlogCategory {
    Insurance = "Insurance",
    Debt = "Debt",
    Refund = "Refund",
    CeaseDesist = "CeaseDesist",
    PropertyDamage = "PropertyDamage",
    Employment = "Employment",
    Landlord = "Landlord",
    Contractor = "Contractor"
}
export enum LetterStatus {
    Sent = "Sent",
    Draft = "Draft",
    ResponseReceived = "ResponseReceived",
    FollowUpNeeded = "FollowUpNeeded",
    Resolved = "Resolved"
}
export enum LetterTone {
    Firm = "Firm",
    Assertive = "Assertive",
    FinalWarning = "FinalWarning"
}
export enum LetterType {
    DebtRecovery = "DebtRecovery",
    LandlordTenant = "LandlordTenant",
    CeaseDesist = "CeaseDesist",
    ContractorDispute = "ContractorDispute",
    InsuranceClaim = "InsuranceClaim",
    PropertyDamage = "PropertyDamage",
    RefundConsumer = "RefundConsumer",
    EmploymentDispute = "EmploymentDispute",
    CreditReportDispute = "CreditReportDispute"
}
export enum ResponseLikelihood {
    Low = "Low",
    High = "High",
    Medium = "Medium"
}
export enum StripePlan {
    Pro = "Pro",
    Business = "Business"
}
export enum UserPlan {
    Pro = "Pro",
    PayPerLetter = "PayPerLetter",
    Free = "Free",
    Business = "Business"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    answerQuestion(question: string, letterId: LetterId): Promise<Result_4>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canGenerateLetter(): Promise<{
        canGenerate: boolean;
        remaining: bigint;
        reason: string;
    }>;
    createArticle(input: CreateArticleInput): Promise<{
        __kind__: "ok";
        ok: BlogArticle;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Create a Stripe Checkout session for a pay-per-letter or plan upgrade.
     * / Returns Stripe session JSON (contains `url` to redirect the user).
     */
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOrUpdateUser(email: string | null): Promise<UserProfile>;
    deleteLetterForUser(id: LetterId): Promise<Result>;
    generateFollowUpLetter(originalLetterId: LetterId): Promise<Result_4>;
    generateLetterStream(formData: LetterFormData, country: string | null): Promise<Result_4>;
    generateStrengthAnalysis(letterId: LetterId): Promise<Result_3>;
    getAdminStats(): Promise<{
        totalLetters: bigint;
        totalUsers: bigint;
        activeSubscriptions: bigint;
    }>;
    getArticleBySlug(slug: string): Promise<BlogArticle | null>;
    getAuditLog(): Promise<Array<[Timestamp, string, string, string]>>;
    getCallerUserRole(): Promise<UserRole>;
    getGmailToken(): Promise<GmailToken | null>;
    getLetter(id: LetterId): Promise<GeneratedLetter | null>;
    /**
     * / Check payment status for a given Stripe session ID.
     */
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserLetters(): Promise<Array<GeneratedLetter>>;
    getUserProfile(): Promise<UserProfile | null>;
    isAnthropicConfigured(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Check whether Stripe has been configured.
     */
    isStripeConfigured(): Promise<boolean>;
    listArticles(categoryFilter: string | null): Promise<Array<BlogArticle>>;
    listPartnershipRequests(): Promise<Array<PartnershipRequest>>;
    recordDownload(id: LetterId): Promise<Result>;
    saveLetter(formData: LetterFormData, letterContent: string): Promise<Result_2>;
    sendLetterViaGmail(recipientEmail: string, letterContent: string, subject: string): Promise<Result_1>;
    setAnthropicKey(key: string): Promise<void>;
    /**
     * / Store the Stripe secret key and allowed countries (admin only).
     */
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    storeGmailToken(accessToken: string, refreshToken: string, expiresAt: bigint): Promise<Result_1>;
    submitPartnershipRequest(input: CreatePartnershipRequestInput): Promise<{
        __kind__: "ok";
        ok: PartnershipRequest;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateArticle(id: string, updates: UpdateArticleInput): Promise<{
        __kind__: "ok";
        ok: BlogArticle;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateLetterStatus(id: LetterId, status: LetterStatus): Promise<Result>;
    updateUserPlan(userId: UserId, plan: StripePlan): Promise<Result>;
}
import type { Address as _Address, BlogArticle as _BlogArticle, BlogCategory as _BlogCategory, CreateArticleInput as _CreateArticleInput, GeneratedLetter as _GeneratedLetter, GmailToken as _GmailToken, LetterFormData as _LetterFormData, LetterId as _LetterId, LetterStatus as _LetterStatus, LetterTone as _LetterTone, LetterType as _LetterType, PartnershipRequest as _PartnershipRequest, PriorContact as _PriorContact, ResponseLikelihood as _ResponseLikelihood, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, StrengthAnalysis as _StrengthAnalysis, StripePlan as _StripePlan, StripeSessionStatus as _StripeSessionStatus, Timestamp as _Timestamp, UpdateArticleInput as _UpdateArticleInput, UserId as _UserId, UserPlan as _UserPlan, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async answerQuestion(arg0: string, arg1: LetterId): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.answerQuestion(arg0, arg1);
                return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.answerQuestion(arg0, arg1);
            return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canGenerateLetter(): Promise<{
        canGenerate: boolean;
        remaining: bigint;
        reason: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.canGenerateLetter();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canGenerateLetter();
            return result;
        }
    }
    async createArticle(arg0: CreateArticleInput): Promise<{
        __kind__: "ok";
        ok: BlogArticle;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(to_candid_CreateArticleInput_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(to_candid_CreateArticleInput_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrUpdateUser(arg0: string | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUser(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUser(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteLetterForUser(arg0: LetterId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLetterForUser(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLetterForUser(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateFollowUpLetter(arg0: LetterId): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.generateFollowUpLetter(arg0);
                return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateFollowUpLetter(arg0);
            return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateLetterStream(arg0: LetterFormData, arg1: string | null): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.generateLetterStream(to_candid_LetterFormData_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateLetterStream(to_candid_LetterFormData_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateStrengthAnalysis(arg0: LetterId): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.generateStrengthAnalysis(arg0);
                return from_candid_Result_3_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateStrengthAnalysis(arg0);
            return from_candid_Result_3_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<{
        totalLetters: bigint;
        totalUsers: bigint;
        activeSubscriptions: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getArticleBySlug(arg0: string): Promise<BlogArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleBySlug(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleBySlug(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLog(): Promise<Array<[Timestamp, string, string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGmailToken(): Promise<GmailToken | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGmailToken();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGmailToken();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLetter(arg0: LetterId): Promise<GeneratedLetter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLetter(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLetter(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserLetters(): Promise<Array<GeneratedLetter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLetters();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLetters();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAnthropicConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAnthropicConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAnthropicConfigured();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listArticles(arg0: string | null): Promise<Array<BlogArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.listArticles(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listArticles(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPartnershipRequests(): Promise<Array<PartnershipRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPartnershipRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPartnershipRequests();
            return result;
        }
    }
    async recordDownload(arg0: LetterId): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDownload(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDownload(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveLetter(arg0: LetterFormData, arg1: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLetter(to_candid_LetterFormData_n22(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_Result_2_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLetter(to_candid_LetterFormData_n22(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_Result_2_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendLetterViaGmail(arg0: string, arg1: string, arg2: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.sendLetterViaGmail(arg0, arg1, arg2);
                return from_candid_Result_1_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendLetterViaGmail(arg0, arg1, arg2);
            return from_candid_Result_1_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAnthropicKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAnthropicKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAnthropicKey(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async storeGmailToken(arg0: string, arg1: string, arg2: bigint): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.storeGmailToken(arg0, arg1, arg2);
                return from_candid_Result_1_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeGmailToken(arg0, arg1, arg2);
            return from_candid_Result_1_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitPartnershipRequest(arg0: CreatePartnershipRequestInput): Promise<{
        __kind__: "ok";
        ok: PartnershipRequest;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPartnershipRequest(arg0);
                return from_candid_variant_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPartnershipRequest(arg0);
            return from_candid_variant_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateArticle(arg0: string, arg1: UpdateArticleInput): Promise<{
        __kind__: "ok";
        ok: BlogArticle;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, to_candid_UpdateArticleInput_n64(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, to_candid_UpdateArticleInput_n64(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLetterStatus(arg0: LetterId, arg1: LetterStatus): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLetterStatus(arg0, to_candid_LetterStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLetterStatus(arg0, to_candid_LetterStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserPlan(arg0: UserId, arg1: StripePlan): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserPlan(arg0, to_candid_StripePlan_n68(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserPlan(arg0, to_candid_StripePlan_n68(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BlogArticle_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogArticle): BlogArticle {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_BlogCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogCategory): BlogCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_GeneratedLetter_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GeneratedLetter): GeneratedLetter {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_LetterFormData_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LetterFormData): LetterFormData {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_LetterStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LetterStatus): LetterStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_LetterTone_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LetterTone): LetterTone {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_LetterType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LetterType): LetterType {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ResponseLikelihood_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResponseLikelihood): ResponseLikelihood {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_StrengthAnalysis_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StrengthAnalysis): StrengthAnalysis {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserPlan_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPlan): UserPlan {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogArticle]): BlogArticle | null {
    return value.length === 0 ? null : from_candid_BlogArticle_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GmailToken]): GmailToken | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeneratedLetter]): GeneratedLetter | null {
    return value.length === 0 ? null : from_candid_GeneratedLetter_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LetterId]): LetterId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    authorName: string;
    publishedAt: bigint;
    updatedAt: bigint;
    excerpt: string;
    category: _BlogCategory;
}): {
    id: string;
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    authorName: string;
    publishedAt: bigint;
    updatedAt: bigint;
    excerpt: string;
    category: BlogCategory;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        slug: value.slug,
        authorName: value.authorName,
        publishedAt: value.publishedAt,
        updatedAt: value.updatedAt,
        excerpt: value.excerpt,
        category: from_candid_BlogCategory_n12(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stripeSubscriptionId: [] | [string];
    userId: _UserId;
    createdAt: _Timestamp;
    plan: _UserPlan;
    email: [] | [string];
    lettersThisMonth: bigint;
    stripeCustomerId: [] | [string];
    totalLetters: bigint;
    currentMonthYear: string;
}): {
    stripeSubscriptionId?: string;
    userId: UserId;
    createdAt: Timestamp;
    plan: UserPlan;
    email?: string;
    lettersThisMonth: bigint;
    stripeCustomerId?: string;
    totalLetters: bigint;
    currentMonthYear: string;
} {
    return {
        stripeSubscriptionId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.stripeSubscriptionId)),
        userId: value.userId,
        createdAt: value.createdAt,
        plan: from_candid_UserPlan_n18(_uploadFile, _downloadFile, value.plan),
        email: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.email)),
        lettersThisMonth: value.lettersThisMonth,
        stripeCustomerId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.stripeCustomerId)),
        totalLetters: value.totalLetters,
        currentMonthYear: value.currentMonthYear
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    responseLikelihood: _ResponseLikelihood;
    strengths: Array<string>;
    improvements: Array<string>;
    score: bigint;
}): {
    responseLikelihood: ResponseLikelihood;
    strengths: Array<string>;
    improvements: Array<string>;
    score: bigint;
} {
    return {
        responseLikelihood: from_candid_ResponseLikelihood_n32(_uploadFile, _downloadFile, value.responseLikelihood),
        strengths: value.strengths,
        improvements: value.improvements,
        score: value.score
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LetterId;
    status: _LetterStatus;
    userId: _UserId;
    createdAt: _Timestamp;
    formData: _LetterFormData;
    letterContent: string;
    originalLetterId: [] | [_LetterId];
    downloadCount: bigint;
    lastDownloadAt: [] | [bigint];
    isFollowUp: boolean;
}): {
    id: LetterId;
    status: LetterStatus;
    userId: UserId;
    createdAt: Timestamp;
    formData: LetterFormData;
    letterContent: string;
    originalLetterId?: LetterId;
    downloadCount: bigint;
    lastDownloadAt?: bigint;
    isFollowUp: boolean;
} {
    return {
        id: value.id,
        status: from_candid_LetterStatus_n41(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        createdAt: value.createdAt,
        formData: from_candid_LetterFormData_n43(_uploadFile, _downloadFile, value.formData),
        letterContent: value.letterContent,
        originalLetterId: record_opt_to_undefined(from_candid_opt_n51(_uploadFile, _downloadFile, value.originalLetterId)),
        downloadCount: value.downloadCount,
        lastDownloadAt: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.lastDownloadAt)),
        isFollowUp: value.isFollowUp
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inaccuracyType: [] | [string];
    senderPhone: string;
    deadlineDays: bigint;
    tone: _LetterTone;
    disputeDescription: string;
    letterType: _LetterType;
    creditSupportingDocs: [] | [Array<string>];
    creditDisputeDescription: [] | [string];
    evidenceItems: Array<string>;
    amountDemanded: [] | [bigint];
    evidenceImages: Array<string>;
    jurisdiction: string;
    accountName: [] | [string];
    currency: string;
    preferredResolution: string;
    senderName: string;
    accountNumber: [] | [string];
    senderEmail: string;
    recipientAddress: _Address;
    recipientName: string;
    recipientRole: string;
    priorContact: _PriorContact;
    senderAddress: _Address;
    incidentDate: string;
    creditBureauName: [] | [string];
}): {
    inaccuracyType?: string;
    senderPhone: string;
    deadlineDays: bigint;
    tone: LetterTone;
    disputeDescription: string;
    letterType: LetterType;
    creditSupportingDocs?: Array<string>;
    creditDisputeDescription?: string;
    evidenceItems: Array<string>;
    amountDemanded?: bigint;
    evidenceImages: Array<string>;
    jurisdiction: string;
    accountName?: string;
    currency: string;
    preferredResolution: string;
    senderName: string;
    accountNumber?: string;
    senderEmail: string;
    recipientAddress: Address;
    recipientName: string;
    recipientRole: string;
    priorContact: PriorContact;
    senderAddress: Address;
    incidentDate: string;
    creditBureauName?: string;
} {
    return {
        inaccuracyType: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.inaccuracyType)),
        senderPhone: value.senderPhone,
        deadlineDays: value.deadlineDays,
        tone: from_candid_LetterTone_n45(_uploadFile, _downloadFile, value.tone),
        disputeDescription: value.disputeDescription,
        letterType: from_candid_LetterType_n47(_uploadFile, _downloadFile, value.letterType),
        creditSupportingDocs: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.creditSupportingDocs)),
        creditDisputeDescription: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.creditDisputeDescription)),
        evidenceItems: value.evidenceItems,
        amountDemanded: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.amountDemanded)),
        evidenceImages: value.evidenceImages,
        jurisdiction: value.jurisdiction,
        accountName: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.accountName)),
        currency: value.currency,
        preferredResolution: value.preferredResolution,
        senderName: value.senderName,
        accountNumber: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.accountNumber)),
        senderEmail: value.senderEmail,
        recipientAddress: value.recipientAddress,
        recipientName: value.recipientName,
        recipientRole: value.recipientRole,
        priorContact: value.priorContact,
        senderAddress: value.senderAddress,
        incidentDate: value.incidentDate,
        creditBureauName: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.creditBureauName))
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Insurance: null;
} | {
    Debt: null;
} | {
    Refund: null;
} | {
    CeaseDesist: null;
} | {
    PropertyDamage: null;
} | {
    Employment: null;
} | {
    Landlord: null;
} | {
    Contractor: null;
}): BlogCategory {
    return "Insurance" in value ? BlogCategory.Insurance : "Debt" in value ? BlogCategory.Debt : "Refund" in value ? BlogCategory.Refund : "CeaseDesist" in value ? BlogCategory.CeaseDesist : "PropertyDamage" in value ? BlogCategory.PropertyDamage : "Employment" in value ? BlogCategory.Employment : "Landlord" in value ? BlogCategory.Landlord : "Contractor" in value ? BlogCategory.Contractor : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Pro: null;
} | {
    PayPerLetter: null;
} | {
    Free: null;
} | {
    Business: null;
}): UserPlan {
    return "Pro" in value ? UserPlan.Pro : "PayPerLetter" in value ? UserPlan.PayPerLetter : "Free" in value ? UserPlan.Free : "Business" in value ? UserPlan.Business : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StrengthAnalysis;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StrengthAnalysis;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_StrengthAnalysis_n30(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
}): ResponseLikelihood {
    return "Low" in value ? ResponseLikelihood.Low : "High" in value ? ResponseLikelihood.High : "Medium" in value ? ResponseLikelihood.Medium : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Sent: null;
} | {
    Draft: null;
} | {
    ResponseReceived: null;
} | {
    FollowUpNeeded: null;
} | {
    Resolved: null;
}): LetterStatus {
    return "Sent" in value ? LetterStatus.Sent : "Draft" in value ? LetterStatus.Draft : "ResponseReceived" in value ? LetterStatus.ResponseReceived : "FollowUpNeeded" in value ? LetterStatus.FollowUpNeeded : "Resolved" in value ? LetterStatus.Resolved : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Firm: null;
} | {
    Assertive: null;
} | {
    FinalWarning: null;
}): LetterTone {
    return "Firm" in value ? LetterTone.Firm : "Assertive" in value ? LetterTone.Assertive : "FinalWarning" in value ? LetterTone.FinalWarning : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DebtRecovery: null;
} | {
    LandlordTenant: null;
} | {
    CeaseDesist: null;
} | {
    ContractorDispute: null;
} | {
    InsuranceClaim: null;
} | {
    PropertyDamage: null;
} | {
    RefundConsumer: null;
} | {
    EmploymentDispute: null;
} | {
    CreditReportDispute: null;
}): LetterType {
    return "DebtRecovery" in value ? LetterType.DebtRecovery : "LandlordTenant" in value ? LetterType.LandlordTenant : "CeaseDesist" in value ? LetterType.CeaseDesist : "ContractorDispute" in value ? LetterType.ContractorDispute : "InsuranceClaim" in value ? LetterType.InsuranceClaim : "PropertyDamage" in value ? LetterType.PropertyDamage : "RefundConsumer" in value ? LetterType.RefundConsumer : "EmploymentDispute" in value ? LetterType.EmploymentDispute : "CreditReportDispute" in value ? LetterType.CreditReportDispute : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n55(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GeneratedLetter;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GeneratedLetter;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GeneratedLetter_n39(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PartnershipRequest;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PartnershipRequest;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BlogArticle;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BlogArticle;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BlogArticle_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GeneratedLetter>): Array<GeneratedLetter> {
    return value.map((x)=>from_candid_GeneratedLetter_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogArticle>): Array<BlogArticle> {
    return value.map((x)=>from_candid_BlogArticle_n10(_uploadFile, _downloadFile, x));
}
function to_candid_BlogCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCategory): _BlogCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_CreateArticleInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateArticleInput): _CreateArticleInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_LetterFormData_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterFormData): _LetterFormData {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_LetterStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterStatus): _LetterStatus {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_LetterTone_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterTone): _LetterTone {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_LetterType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterType): _LetterType {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_StripePlan_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StripePlan): _StripePlan {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateArticleInput_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateArticleInput): _UpdateArticleInput {
    return to_candid_record_n65(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inaccuracyType?: string;
    senderPhone: string;
    deadlineDays: bigint;
    tone: LetterTone;
    disputeDescription: string;
    letterType: LetterType;
    creditSupportingDocs?: Array<string>;
    creditDisputeDescription?: string;
    evidenceItems: Array<string>;
    amountDemanded?: bigint;
    evidenceImages: Array<string>;
    jurisdiction: string;
    accountName?: string;
    currency: string;
    preferredResolution: string;
    senderName: string;
    accountNumber?: string;
    senderEmail: string;
    recipientAddress: Address;
    recipientName: string;
    recipientRole: string;
    priorContact: PriorContact;
    senderAddress: Address;
    incidentDate: string;
    creditBureauName?: string;
}): {
    inaccuracyType: [] | [string];
    senderPhone: string;
    deadlineDays: bigint;
    tone: _LetterTone;
    disputeDescription: string;
    letterType: _LetterType;
    creditSupportingDocs: [] | [Array<string>];
    creditDisputeDescription: [] | [string];
    evidenceItems: Array<string>;
    amountDemanded: [] | [bigint];
    evidenceImages: Array<string>;
    jurisdiction: string;
    accountName: [] | [string];
    currency: string;
    preferredResolution: string;
    senderName: string;
    accountNumber: [] | [string];
    senderEmail: string;
    recipientAddress: _Address;
    recipientName: string;
    recipientRole: string;
    priorContact: _PriorContact;
    senderAddress: _Address;
    incidentDate: string;
    creditBureauName: [] | [string];
} {
    return {
        inaccuracyType: value.inaccuracyType ? candid_some(value.inaccuracyType) : candid_none(),
        senderPhone: value.senderPhone,
        deadlineDays: value.deadlineDays,
        tone: to_candid_LetterTone_n24(_uploadFile, _downloadFile, value.tone),
        disputeDescription: value.disputeDescription,
        letterType: to_candid_LetterType_n26(_uploadFile, _downloadFile, value.letterType),
        creditSupportingDocs: value.creditSupportingDocs ? candid_some(value.creditSupportingDocs) : candid_none(),
        creditDisputeDescription: value.creditDisputeDescription ? candid_some(value.creditDisputeDescription) : candid_none(),
        evidenceItems: value.evidenceItems,
        amountDemanded: value.amountDemanded ? candid_some(value.amountDemanded) : candid_none(),
        evidenceImages: value.evidenceImages,
        jurisdiction: value.jurisdiction,
        accountName: value.accountName ? candid_some(value.accountName) : candid_none(),
        currency: value.currency,
        preferredResolution: value.preferredResolution,
        senderName: value.senderName,
        accountNumber: value.accountNumber ? candid_some(value.accountNumber) : candid_none(),
        senderEmail: value.senderEmail,
        recipientAddress: value.recipientAddress,
        recipientName: value.recipientName,
        recipientRole: value.recipientRole,
        priorContact: value.priorContact,
        senderAddress: value.senderAddress,
        incidentDate: value.incidentDate,
        creditBureauName: value.creditBureauName ? candid_some(value.creditBureauName) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    authorName: string;
    excerpt: string;
    category: BlogCategory;
}): {
    title: string;
    content: string;
    isPublished: boolean;
    slug: string;
    authorName: string;
    excerpt: string;
    category: _BlogCategory;
} {
    return {
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        slug: value.slug,
        authorName: value.authorName,
        excerpt: value.excerpt,
        category: to_candid_BlogCategory_n7(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title?: string;
    content?: string;
    isPublished?: boolean;
    authorName?: string;
    excerpt?: string;
    category?: BlogCategory;
}): {
    title: [] | [string];
    content: [] | [string];
    isPublished: [] | [boolean];
    authorName: [] | [string];
    excerpt: [] | [string];
    category: [] | [_BlogCategory];
} {
    return {
        title: value.title ? candid_some(value.title) : candid_none(),
        content: value.content ? candid_some(value.content) : candid_none(),
        isPublished: value.isPublished ? candid_some(value.isPublished) : candid_none(),
        authorName: value.authorName ? candid_some(value.authorName) : candid_none(),
        excerpt: value.excerpt ? candid_some(value.excerpt) : candid_none(),
        category: value.category ? candid_some(to_candid_BlogCategory_n7(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterTone): {
    Firm: null;
} | {
    Assertive: null;
} | {
    FinalWarning: null;
} {
    return value == LetterTone.Firm ? {
        Firm: null
    } : value == LetterTone.Assertive ? {
        Assertive: null
    } : value == LetterTone.FinalWarning ? {
        FinalWarning: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterType): {
    DebtRecovery: null;
} | {
    LandlordTenant: null;
} | {
    CeaseDesist: null;
} | {
    ContractorDispute: null;
} | {
    InsuranceClaim: null;
} | {
    PropertyDamage: null;
} | {
    RefundConsumer: null;
} | {
    EmploymentDispute: null;
} | {
    CreditReportDispute: null;
} {
    return value == LetterType.DebtRecovery ? {
        DebtRecovery: null
    } : value == LetterType.LandlordTenant ? {
        LandlordTenant: null
    } : value == LetterType.CeaseDesist ? {
        CeaseDesist: null
    } : value == LetterType.ContractorDispute ? {
        ContractorDispute: null
    } : value == LetterType.InsuranceClaim ? {
        InsuranceClaim: null
    } : value == LetterType.PropertyDamage ? {
        PropertyDamage: null
    } : value == LetterType.RefundConsumer ? {
        RefundConsumer: null
    } : value == LetterType.EmploymentDispute ? {
        EmploymentDispute: null
    } : value == LetterType.CreditReportDispute ? {
        CreditReportDispute: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LetterStatus): {
    Sent: null;
} | {
    Draft: null;
} | {
    ResponseReceived: null;
} | {
    FollowUpNeeded: null;
} | {
    Resolved: null;
} {
    return value == LetterStatus.Sent ? {
        Sent: null
    } : value == LetterStatus.Draft ? {
        Draft: null
    } : value == LetterStatus.ResponseReceived ? {
        ResponseReceived: null
    } : value == LetterStatus.FollowUpNeeded ? {
        FollowUpNeeded: null
    } : value == LetterStatus.Resolved ? {
        Resolved: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StripePlan): {
    Pro: null;
} | {
    Business: null;
} {
    return value == StripePlan.Pro ? {
        Pro: null
    } : value == StripePlan.Business ? {
        Business: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCategory): {
    Insurance: null;
} | {
    Debt: null;
} | {
    Refund: null;
} | {
    CeaseDesist: null;
} | {
    PropertyDamage: null;
} | {
    Employment: null;
} | {
    Landlord: null;
} | {
    Contractor: null;
} {
    return value == BlogCategory.Insurance ? {
        Insurance: null
    } : value == BlogCategory.Debt ? {
        Debt: null
    } : value == BlogCategory.Refund ? {
        Refund: null
    } : value == BlogCategory.CeaseDesist ? {
        CeaseDesist: null
    } : value == BlogCategory.PropertyDamage ? {
        PropertyDamage: null
    } : value == BlogCategory.Employment ? {
        Employment: null
    } : value == BlogCategory.Landlord ? {
        Landlord: null
    } : value == BlogCategory.Contractor ? {
        Contractor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
